### PR TITLE
Update workspace.ts

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
Fix incorrect file paths formatting that generates an error when the extension loads

### CODE REVIEW

**Comment by tintoy** [comment]
Thanks, nice catch!

**Comment by tintoy** [comment]
Will publish a new version of the extension when I get back to my computer :)

**Comment by tintoy** [comment]
Hi @ChrisChinchilla - made a slight tweak to your fix (15be4fe7fa38a9da9ddb9b23f30f54b0107fe948) based on syntax examples from the VSCode codebase:

https://github.com/Microsoft/vscode/blob/d7abec3a2c0157e1ee10f23c78a614f0902e0d27/src/vs/base/common/glob.ts#L243

**Comment by tintoy** [comment]
Published `v0.1.4` :)

**Comment by tintoy** [comment]
Published `v0.1.5` - turns out this exposed another issue which has also now been fixed :)

(apologies, it's been a while since I've done any work on this project)

**Comment by ChrisChinchilla** [comment]
No worries @tintoy thanks!

**Pull request merged**
